version: '3.7'

networks:
  michibaum-network:

services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    expose:
      - 9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ${PORTAINER_HOST_PATH}:/data  IMPLEMENT WITH A DOCKER PLUGIN
    networks:
      - michibaum-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 200mb
        reservations:
          memory: 200mb
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        max_attempts: 20
        window: 10m