version: '3.7'

networks:
  michibaum-network:
    driver: overlay

services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/MichiBaum-Portainer/data:/data
    networks:
      - michibaum-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 200mb
        reservations:
          memory: 200mb
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        max_attempts: 20
        window: 10m
      placement:
        constraints: [node.labels.manager == true ] # docker node update --label-add manager=true <node id>